language: node_js
sudo: false
node_js:
- '8'
before_script:
- npm install -g firebase-tools
install:
- npm install
script:
- npm run lint
- npm run cover
- npm run build
branches:
  only:
  - master
after_success:
- firebase deploy --token $FIREBASE_TOKEN --non-interactive
